### PR TITLE
Added a const prefix to input parameters (non-ref and non-out)

### PR DESCRIPTION
**Pull request by JmgrArt**

### CODE REVIEW

**Comment by jacksondunstan** [comment]
@JmgrArt, could you please explain why this change is beneficial?

**Comment by JmgrArt** [comment]
This change sets non-ref and non-out parameters in generated C++ functions as const. This prevents users of these functions to try and modify input parameters. Without const, in the case of primitives, this would compile but have no effect, leading to bugs. In addition, since classes and managed structs are passed as references this also allows creating them on the fly without having to declare them.
For example, if I want to set the name of the MonoBehaviour object in C++ using the SetName setter function without this change I would have to write:
`String value("My name");
SetName(value);`
With this change I could write:
`SetName(String("My name"));`
Or even better, since the String constructor taking a const char * is implicit by default:
`SetName("My name");`
It also participates in the [const-correctess](https://isocpp.org/wiki/faq/const-correctness).

**Comment by jacksondunstan** [comment]
Hi @JmgrArt, thanks for the pull request and for providing the requested explanation. C# reference type parameters may be mutated by the function. Consider this method:

```cs
public void Mutate(Person p)
{
    p.First = "Jackson";
    p.Last = "Dunstan";
}
```

This is extremely common in C# programming. If `const` were added on the C++ side, it would provide the illusion that the parameter would not be mutated. In fact, the parameter may be mutated which users would likely find quite surprising since it is `const`. Technically, the C++ object passed a parameter would not be modified, but the C# counterpart to this object would be. Consider this example in C++:

```cpp
Person p = Person::CreateJamesKirk();
Debug::Log(p.GetFirst()); // "James"
Debug::Log(p.GetLast()); // "Kirk"
Mutate(p); // Mutate's parameter is 'const', so no mutation is expected
Debug::Log(p.GetFirst()); // "Jackson"
Debug::Log(p.GetLast()); // "Dunstan"
```

In this example, only the C++ `Person` is unmodified. Since it contains only a `Handle` field and that field wasn't modified, `const` has been obeyed. However, the illusion these bindings are creating for users of the project is that the C++ object is a representation of the corresponding C# object. That C# object _has_ been modified, so the `const` appears to have been violated even when that would have been illegal in C++ (except for "casting away the const-ness" with something like `const_cast`).

Given this surprising behavior, I think it's best to leave out the `const` and therefore make generated C++ interfaces more usable.

**Comment by JmgrArt** [comment]
Thanks for the detailed answer. Could it be possible to add some kind of flag in the NativeScriptTypes.json file to indicate that the generated parameter should be const? This could also apply to member function constness and getters.
Something like that:
```
{
        "Name": "UnityEngine.Debug",
        "Methods": [
                {
                        "Name": "Log",
                        "ParamTypes": [
                                "System.Object"
                        ],
                        "ParamFlags": [
                                "const"
                        ]
                }
        ]
}
```

**Comment by jacksondunstan** [comment]
Hi @JmgrArt, thanks for the idea to add flags like this to the JSON config. I've considered adding such fine-tuning parameters to the JSON config in the past, but currently haven't prioritized it as there's more pressing work to be done on the project. I've taken a note though about this idea and will consider adding it at a later stage.

**Pull request closed without merging**
