### PR TITLE
Set getter methods to be const

### PR DESCRIPTION
**Pull request by JmgrArt**

### CODE REVIEW

**Comment by jacksondunstan** [comment]
@JmgrArt, could you please explain why this change is beneficial?

**Comment by JmgrArt** [comment]
The const keyword in C++ allows the developer to indicate that a member function will have no effect on the object (this). It guarantees that any call of this function will not modify the logic state and enforces the [const-correctess](https://isocpp.org/wiki/faq/const-correctness).
This change would apply the const-correctness for getters.

**Comment by jacksondunstan** [comment]
Hi @JmgrArt, thanks for the pull request and for providing the requested explanation. C# properties' `get` functions are not guaranteed to avoid mutating the object. Consider this class:
```cs
public class IntVal
{
    private int val;
    
    public int Val
    {
        get { val++; return val; }
        set { val = value; }
    }
}
```

While this design is definitely surprising to users of the class and should be avoided, it is possible in the C# language. If `const` were added on the C++ side, it would provide the illusion that the object would not be mutated. In fact, the object may be mutated which users would likely find just as surprising as the mutating `get` function. Given this mismatch, I think it's best to leave off the `const` keyword to avoid surprise and therefore make generated C++ interfaces more usable.

**Comment by JmgrArt** [comment]
Good point, C# is definitely more lax regarding getters.

**Pull request closed without merging**
