### PR TITLE
Use C++ headers instead of C headers

### PR DESCRIPTION
**Pull request by JmgrArt**

### CODE REVIEW

**Comment by jacksondunstan** [comment]
@JmgrArt, could you please explain why this change is beneficial?

**Comment by JmgrArt** [comment]
This pull request would:
- Improve coherence: why use C headers within C++ code, since C++ standard headers are available?
- Reduce name collision: C++ headers for the standard library are in the std namespace ; name collisions are less likely to occur

**Comment by jacksondunstan** [comment]
Hi @JmgrArt, thanks for the pull request and for providing the requested explanation. Per the C++ standard, C++ headers _will_ provide everything in the `std` namespace and _may_ also provide everything in the global namespace. Conversely, the C headers _will_ provide everything in the global namespace and _may_ provide everything in the `std` namespace. Right now this project is using the global namespace, which I feel is reasonable for types like `int32_t` and functions like `memset`. I _could_ prefix all of these with `std::` or add `using namespace std` at some high level of scoping, but there doesn't seem to be much advantage to that and, in the case of prefixing, will make the code harder to read by adding "noise" to it: `std::int32_t` instead of just `int32_t`. Finally, the project currently has no dependency on the C++ Standard Library (a.k.a. STL) and using the C++ headers would add that dependency. So for these reasons I think I'll stick with the C headers.

**Comment by JmgrArt** [comment]
I understand your reasons. Your wrote in your profile that you are working in the videogame industry, and I know that development within this context has special constraints (no STL for example). I started myself as a videogame developer some time ago. Anyway, thanks for the detailed answer.

**Pull request closed without merging**
